### ISSUE TITLE
Mise à jour du planning

### ISSUE THREAD

**Issue by 73VW** [HE-Arc/FreeGo2#42]
D'après [cette page](https://github.com/HE-Arc/FreeGo2/wiki/planning) le planning n'a pas été mis à jour depuis début mars. 

Difficile de suivre l'avancement dans ce cas.

**Comment by grunenwald** [comment]
Perso, je n'impose pas de faire/partager les MAJ du Gantt sur l'avancement, vu que je fais les revues chaque semaine. Tu peux lui demander si tu le souhaites, sinon, le board du projet est à jour, il donne une bonne idée de l'avance : https://github.com/HE-Arc/FreeGo2/projects/1

**Comment by 73VW** [comment]
J'ai vu pour le board mais j'aurais aimé pouvoir comparer l'avancement par rapport au planning de base 😉

**Comment by Kevin-Laipe** [comment]
J'ai mis à jour la plage du planning avec un screen du gantt à jour ;)

**Comment by 73VW** [comment]
Merveilleux, merci beaucoup!
